# -*- coding: utf-8 -*-

class Token(object):
    """Base class for all token's implementations."""

    def __init__(self, request, username, expire):
        """Initialize function

        :param request: flask.request object

        :param username: username in Linux
        """
        self.request = request
        self.username = username
        self.expire = expire
        self.salt = None

    def generate(self):
        """Generates token for data passed in __init__ function"""
        raise NotImplementedError("Token::generate must be implemented!")

    def validate(self, token):
        """Checks if token generated by generate function is equal to one
        received from user
        """
        return token == self.generate()
